name: Build Windows EXE

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Chocolatey packages (rcedit, innosetup)
        run: |
          choco install -y rcedit
          choco install -y innosetup

      - name: Build frontend
        working-directory: ./offline_ui
        run: |
          npm ci
          npm run build

      - name: Prepare build payload (Python helper)
        run: |
          python tools/build_windows.py --prepare --version 1.0.0 --icon offline_ui/public/cridergpt.ico

      - name: Install Python deps and PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run PyInstaller (spec)
        run: |
          pyinstaller --clean --noconfirm tools/cridergpt.spec

      - name: Post-process EXE (rcedit) and optional signing
        shell: powershell
        run: |
          $exe = Join-Path $PWD 'dist\CriderGPT_Offline.exe'
          Write-Host "Post-processing $exe"
          # apply version metadata and icon (build_windows_post.ps1 expects rcedit present)
          .\tools\build_windows_post.ps1 -ExePath $exe -VersionFile .\tools\version_metadata.json -IconPath .\offline_ui\public\cridergpt.ico

      - name: Build Inno Setup installer
        shell: powershell
        run: |
          $iscc = '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"'
          if (Test-Path 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe') {
            & $iscc ..\build_installer.iss
          } else {
            Write-Host 'ISCC not found; skipping installer packaging'
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cridergpt-windows-build
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.msix
            dist/*Setup*.exe
